/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedAgentMemoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "clearSecret"
      | "decryptionReady"
      | "getDecryptedSecret"
      | "hasSecret"
      | "onSecretDecrypted"
      | "requestSecretDecryption"
      | "storeSecret"
      | "verifySecret"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DecryptionRequested"
      | "MemoryCleared"
      | "MemoryStored"
      | "SecretDecrypted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "clearSecret",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decryptionReady",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecryptedSecret",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasSecret",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onSecretDecrypted",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestSecretDecryption",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "storeSecret",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySecret",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "clearSecret",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptionReady",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecryptedSecret",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasSecret", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onSecretDecrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestSecretDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeSecret",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySecret",
    data: BytesLike
  ): Result;
}

export namespace DecryptionRequestedEvent {
  export type InputTuple = [agent: AddressLike, requestId: BigNumberish];
  export type OutputTuple = [agent: string, requestId: bigint];
  export interface OutputObject {
    agent: string;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemoryClearedEvent {
  export type InputTuple = [agent: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [agent: string, timestamp: bigint];
  export interface OutputObject {
    agent: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemoryStoredEvent {
  export type InputTuple = [agent: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [agent: string, timestamp: bigint];
  export interface OutputObject {
    agent: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SecretDecryptedEvent {
  export type InputTuple = [agent: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [agent: string, timestamp: bigint];
  export interface OutputObject {
    agent: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedAgentMemory extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedAgentMemory;
  waitForDeployment(): Promise<this>;

  interface: EncryptedAgentMemoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  clearSecret: TypedContractMethod<[], [void], "nonpayable">;

  decryptionReady: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getDecryptedSecret: TypedContractMethod<[], [bigint], "view">;

  hasSecret: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  onSecretDecrypted: TypedContractMethod<
    [requestId: BigNumberish, decryptedValue: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestSecretDecryption: TypedContractMethod<[], [void], "nonpayable">;

  storeSecret: TypedContractMethod<
    [encryptedSecret: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  verifySecret: TypedContractMethod<
    [guessSecret: BytesLike, inputProof: BytesLike],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "clearSecret"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "decryptionReady"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getDecryptedSecret"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasSecret"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "onSecretDecrypted"
  ): TypedContractMethod<
    [requestId: BigNumberish, decryptedValue: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestSecretDecryption"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "storeSecret"
  ): TypedContractMethod<
    [encryptedSecret: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifySecret"
  ): TypedContractMethod<
    [guessSecret: BytesLike, inputProof: BytesLike],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "DecryptionRequested"
  ): TypedContractEvent<
    DecryptionRequestedEvent.InputTuple,
    DecryptionRequestedEvent.OutputTuple,
    DecryptionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "MemoryCleared"
  ): TypedContractEvent<
    MemoryClearedEvent.InputTuple,
    MemoryClearedEvent.OutputTuple,
    MemoryClearedEvent.OutputObject
  >;
  getEvent(
    key: "MemoryStored"
  ): TypedContractEvent<
    MemoryStoredEvent.InputTuple,
    MemoryStoredEvent.OutputTuple,
    MemoryStoredEvent.OutputObject
  >;
  getEvent(
    key: "SecretDecrypted"
  ): TypedContractEvent<
    SecretDecryptedEvent.InputTuple,
    SecretDecryptedEvent.OutputTuple,
    SecretDecryptedEvent.OutputObject
  >;

  filters: {
    "DecryptionRequested(address,uint256)": TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;
    DecryptionRequested: TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;

    "MemoryCleared(address,uint256)": TypedContractEvent<
      MemoryClearedEvent.InputTuple,
      MemoryClearedEvent.OutputTuple,
      MemoryClearedEvent.OutputObject
    >;
    MemoryCleared: TypedContractEvent<
      MemoryClearedEvent.InputTuple,
      MemoryClearedEvent.OutputTuple,
      MemoryClearedEvent.OutputObject
    >;

    "MemoryStored(address,uint256)": TypedContractEvent<
      MemoryStoredEvent.InputTuple,
      MemoryStoredEvent.OutputTuple,
      MemoryStoredEvent.OutputObject
    >;
    MemoryStored: TypedContractEvent<
      MemoryStoredEvent.InputTuple,
      MemoryStoredEvent.OutputTuple,
      MemoryStoredEvent.OutputObject
    >;

    "SecretDecrypted(address,uint256)": TypedContractEvent<
      SecretDecryptedEvent.InputTuple,
      SecretDecryptedEvent.OutputTuple,
      SecretDecryptedEvent.OutputObject
    >;
    SecretDecrypted: TypedContractEvent<
      SecretDecryptedEvent.InputTuple,
      SecretDecryptedEvent.OutputTuple,
      SecretDecryptedEvent.OutputObject
    >;
  };
}
