/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedAgentMemoryInterface extends Interface {
  getFunction(
    nameOrSignature: "storeSecret" | "verifySecret"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SecretStored"): EventFragment;

  encodeFunctionData(
    functionFragment: "storeSecret",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySecret",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "storeSecret",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySecret",
    data: BytesLike
  ): Result;
}

export namespace SecretStoredEvent {
  export type InputTuple = [agent: AddressLike];
  export type OutputTuple = [agent: string];
  export interface OutputObject {
    agent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedAgentMemory extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedAgentMemory;
  waitForDeployment(): Promise<this>;

  interface: EncryptedAgentMemoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  storeSecret: TypedContractMethod<
    [_encryptedSecret: BytesLike, _proof: BytesLike],
    [void],
    "nonpayable"
  >;

  verifySecret: TypedContractMethod<
    [_guessSecret: BytesLike, _proof: BytesLike],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "storeSecret"
  ): TypedContractMethod<
    [_encryptedSecret: BytesLike, _proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifySecret"
  ): TypedContractMethod<
    [_guessSecret: BytesLike, _proof: BytesLike],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "SecretStored"
  ): TypedContractEvent<
    SecretStoredEvent.InputTuple,
    SecretStoredEvent.OutputTuple,
    SecretStoredEvent.OutputObject
  >;

  filters: {
    "SecretStored(address)": TypedContractEvent<
      SecretStoredEvent.InputTuple,
      SecretStoredEvent.OutputTuple,
      SecretStoredEvent.OutputObject
    >;
    SecretStored: TypedContractEvent<
      SecretStoredEvent.InputTuple,
      SecretStoredEvent.OutputTuple,
      SecretStoredEvent.OutputObject
    >;
  };
}
